# Configuration for matrix multiply algorithm evolution (3*3*3)
max_iterations: 100  # Increased iterations
checkpoint_interval: 10
log_level: "INFO"

# LLM configuration
llm:
  # primary_model: "google/gemini-2.0-flash-001"
  # primary_model: "llama3.1-8b"
  primary_model: "deepseek-v3"
  primary_model_weight: 0.7
  # secondary_model: "anthropic/claude-3.7-sonnet"
  # secondary_model: "llama-4-scout-17b-16e-instruct"
  secondary_model : "deepseek-r1-250528"
  secondary_model_weight: 0.3
  # api_base: "https://openrouter.ai/api/v1"
  # api_base: "https://api.cerebras.ai/v1"
  api_base: "https://qianfan.baidubce.com/v2"
  api_key: "bce-v3/<qianfan-api-key>"
  temperature: 0.7
  top_p: 0.95
  max_tokens: 8192
  timeout: 600

# Prompt configuration
prompt:
  system_message: |
    You are a state-of-the-art python code completion system that will be used as part of a genetic algorithm to optimize matrix multiplication algorithms to use AS FEW scalar multiplications AS POSSIBLE. 
    Focus on design the 3*3 and 3*3 matrix multiply algorithm from scratch, try best for new ideas with hint from Strassen's work for 2*2 matrix multiplication. Here are some more instructions for this task: 
      1. Think step by step to outline an algorithm, and then implement it.
      2. DO NOT use Strassen or LADERMAN's algorithm directly on your implementation. 
      3. DOUBLE CHECK your implementation step by step to ENSURE its correctness.
  num_top_programs: 3
  use_template_stochasticity: true

# Database configuration
database:
  population_size: 60  # Increased population for more diversity
  archive_size: 25
  num_islands: 4
  elite_selection_ratio: 0.3
  exploitation_ratio: 0.7

# Evaluator configuration
evaluator:
  timeout: 60
  cascade_evaluation: false
  parallel_evaluations: 4
  use_llm_feedback: false

# Evolution settings
diff_based_evolution: false  # Use full rewrites instead of diffs
allow_full_rewrites: true    # Allow full rewrites for constructor functions
